package com.mep.database.mapper;

import com.mep.database.entity.Administrator;
import com.mep.database.entity.AdministratorExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @SelectProvider(type=AdministratorSqlProvider.class, method="countByExample")
    long countByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @DeleteProvider(type=AdministratorSqlProvider.class, method="deleteByExample")
    int deleteByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @Delete({
        "delete from \"administrator\"",
        "where \"admin_id\" = #{adminId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @Insert({
        "insert into \"administrator\" (\"admin_id\", \"admin_name\", ",
        "\"admin_email\", \"admin_password\", ",
        "\"created_date\", \"updated_date\")",
        "values (#{adminId,jdbcType=INTEGER}, #{adminName,jdbcType=VARCHAR}, ",
        "#{adminEmail,jdbcType=VARCHAR}, #{adminPassword,jdbcType=VARCHAR}, ",
        "#{createdDate,jdbcType=TIMESTAMP}, #{updatedDate,jdbcType=TIMESTAMP})"
    })
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @InsertProvider(type=AdministratorSqlProvider.class, method="insertSelective")
    int insertSelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @SelectProvider(type=AdministratorSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="admin_id", property="adminId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="admin_name", property="adminName", jdbcType=JdbcType.VARCHAR),
        @Result(column="admin_email", property="adminEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="admin_password", property="adminPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_date", property="createdDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_date", property="updatedDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Administrator> selectByExampleWithRowbounds(AdministratorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @SelectProvider(type=AdministratorSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="admin_id", property="adminId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="admin_name", property="adminName", jdbcType=JdbcType.VARCHAR),
        @Result(column="admin_email", property="adminEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="admin_password", property="adminPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_date", property="createdDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_date", property="updatedDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Administrator> selectByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @Select({
        "select",
        "\"admin_id\", \"admin_name\", \"admin_email\", \"admin_password\", \"created_date\", ",
        "\"updated_date\"",
        "from \"administrator\"",
        "where \"admin_id\" = #{adminId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="admin_id", property="adminId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="admin_name", property="adminName", jdbcType=JdbcType.VARCHAR),
        @Result(column="admin_email", property="adminEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="admin_password", property="adminPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_date", property="createdDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_date", property="updatedDate", jdbcType=JdbcType.TIMESTAMP)
    })
    Administrator selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @UpdateProvider(type=AdministratorSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @UpdateProvider(type=AdministratorSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @UpdateProvider(type=AdministratorSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    @Update({
        "update \"administrator\"",
        "set \"admin_name\" = #{adminName,jdbcType=VARCHAR},",
          "\"admin_email\" = #{adminEmail,jdbcType=VARCHAR},",
          "\"admin_password\" = #{adminPassword,jdbcType=VARCHAR},",
          "\"created_date\" = #{createdDate,jdbcType=TIMESTAMP},",
          "\"updated_date\" = #{updatedDate,jdbcType=TIMESTAMP}",
        "where \"admin_id\" = #{adminId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Administrator record);
}